# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.Earl>

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: train/loss # quantity to be monitored, must be specified !!!
  min_delta: 0.001 # minimum change in the monitored quantity to qualify as an >
  patience: 8 # number of checks with no improvement after which training will >
  verbose: True # verbosity mode
  mode: "min" # "max" means higher metric value is better, can be also "min"
  strict: True # whether to crash the training if monitor is not found in the v>
  check_finite: True # when set True, stops training when the monitor becomes N>
  stopping_threshold: null # stop training immediately once the monitored quant>
  divergence_threshold: null # stop training as soon as the monitored quantity >
  check_on_train_epoch_end: null # whether to run early stopping at the end of >
  # log_rank_zero_only: False  # this keyword argument isn't available in stabl>



